### ISSUE TITLE
Project module does not load directories while using theme

### ISSUE THREAD

**Issue by MattMitchell90** [mallowigi/material-theme-jetbrains-docs#211]
I am getting following error when opening a project. This was working but suddenly it stopped loading directories in Project module.

null
java.lang.NullPointerException
	at com.chrisrm.idea.icons.Associations.findAssociationForFile(Associations.java:65)
	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:62)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:40)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:183)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:138)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:278)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:163)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:140)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:138)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:105)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:162)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by MattMitchell90** [comment]
[https://i.imgur.com/tb2EbVL.png](url)

**Comment by MattMitchell90** [comment]
![idea64_2018-03-30_15-57-19](https://user-images.githubusercontent.com/25928813/38151910-25b68e12-3433-11e8-9dfc-9aad1d5af069.png)
