### ISSUE TITLE
Got a `null` exception

### ISSUE THREAD

**Issue by epistemex** [mallowigi/material-theme-jetbrains-docs#214]
Got a null exception from the theme. It seem to be related to the [Database Navigator v.3.0.8222](https://www.jetbrains.net/confluence/display/CONTEST/Database+Navigator) plugin (there are several rendering glitches in the plugin's GUI):

WebStorm details:

```text
WebStorm 2018.1.5
Build #WS-181.5281.31, built on June 14, 2018
xxx
xxx
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 xxxxx
```

Theme details:  
Version: 2.4.1.2-2018.1

Steps taken: simply running a SQL query or doing something else that will force the DN plugin to open a window belonging to it, after perhaps being dormant a few minutes. Doesn't seem to be any particular order in order to reproduce (random memory issues?).

That being said: the theme works fine without DN - not sure if it's an issue with DN or theme or simply the combination, but reporting here as the error came via the theme:

```text
null
java.lang.NullPointerException
	at com.chrisrm.idea.ui.MTTableHeaderUI$MTDefaultRenderer.getTableCellRendererComponent(MTTableHeaderUI.java:96)
	at com.dci.intellij.dbn.common.ui.table.DBNTable.accommodateColumnSize(DBNTable.java:201)
	at com.dci.intellij.dbn.common.ui.table.DBNTable.accommodateColumnsSize(DBNTable.java:166)
	at com.dci.intellij.dbn.data.grid.ui.table.basic.BasicTable.tableChanged(BasicTable.java:196)
	at com.dci.intellij.dbn.data.model.basic.BasicDataModel$4.execute(BasicDataModel.java:266)
	at com.dci.intellij.dbn.common.thread.SynchronizedTask.run(SynchronizedTask.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Example image of glitches (usually worse but I guess it got shy when taking a snapshot):

![image](https://user-images.githubusercontent.com/26116778/41764983-4fa957be-75c8-11e8-80ec-b4e5f7daf350.png)

**Comment by epistemex** [comment]
I appears to also happen with native dialogs as well. There is of course the slight chance of being a display driver problem (unless others can confirm the same issue) but there is no update available to test with atm so cannot confirm/eliminate this.

![2018-06-29_09-27-40](https://user-images.githubusercontent.com/26116778/42098030-55a2daa2-7b7f-11e8-9143-0eab0fd78339.jpg)

(Settings, Register File type)
