### ISSUE TITLE
Exception thrown when Alt+Click dragging tabs to other open Intellij windows.

### ISSUE THREAD

**Issue by huffstler** [mallowigi/material-theme-jetbrains-docs#243]
This doesn't happen immediately after clicking and dragging tabs, but after multiple times of doing it (<10) it will freeze the whole Intellij screen that the tabs are on. Other open Intellij windows still work as expected.

```
java.lang.ClassCastException: javax.swing.JLabel cannot be cast to com.intellij.openapi.fileEditor.impl.EditorWindow$TComp
	at com.intellij.openapi.fileEditor.impl.EditorWindow.getEditorAt(EditorWindow.java:1076)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.getEditors(EditorWindow.java:639)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.getOpenFiles(EditorsSplitters.java:294)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getOpenFiles(FileEditorManagerImpl.java:1260)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.filesWithTheSameName(UniqueVFilePathBuilderImpl.java:111)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:88)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:38)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:44)
	at com.chrisrm.idea.tabs.MTEditorUpperTabs.getEditorTabTitle(MTEditorUpperTabs.java:144)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider.getEditorTabTitle(EditorTabTitleProvider.java:21)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:18)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.updateFileName(EditorWindow.java:901)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.updateFileName(EditorsSplitters.java:400)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$4.run(FileEditorManagerImpl.java:435)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:336)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:326)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:276)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:3101)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:287)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:245)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:224)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mallowigi** [comment]
cannot reproduce
